environment:
  matrix:
    - PYTHON: "Python39"
      BUILD_ARCH: "x86"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    - PYTHON: "Python310"
      BUILD_ARCH: "x86"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    - PYTHON: "Python311"
      BUILD_ARCH: "x86"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022

    - PYTHON: "Python39-x64"
      BUILD_ARCH: "x64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    - PYTHON: "Python310-x64"
      BUILD_ARCH: "x64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    - PYTHON: "Python311-x64"
      BUILD_ARCH: "x64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022

build_script:
#  - '.\venv\Scripts\python setup.py build_ext --inplace'
#  - '.\venv\Scripts\python setup.py bdist_wheel'
  - 'move omniORBpy omniORB\src\lib'

  - 'cd omniORB'
  - 'set PATH=%PATH%;%CD%\bin\x86_win32'

  # doesn't work: - 'echo platform = x86_win32_vs_14>>config\config.mk'
  - 'sed -i "s/.*Uncomment one of the following platform lines.*/platform = x86_win32_vs_14/" config/config.mk'
  - 'echo PYTHON = /cygdrive/c/%PYTHON%/python>>mk\platforms\x86_win32_vs_14.mk'

# install cygwin make
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %BUILD_ARCH%'
  - 'set path=%path%;c:\cygwin\bin;c:\%PYTHON%'
  - 'set path=c:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86;c:\Program Files (x86)\Windows Kits\10\bin\10.0.17134.0\x86\;%PATH%'
  - 'cd src'
  - 'make export'
  - 'cd lib\omniORBpy'
  - 'make export'
  - 'cd ..\..\..\..'
  - 'c:\%PYTHON%\python.exe -m pip install wheel'
  - 'c:\%PYTHON%\python.exe setup.py bdist_wheel'

# "C:\Users\kevin\Documents\omniorb-svn\actual-svn\omniORB\omniORB\src\tool\omniidl\cxx\idlpython.d"
# replace /C/Python with /cygdrive/C/Python
# omkdepend creates this wrong

artifacts:
  - path: 'dist/*whl'

test: off
